FROM amazoncorretto:21-alpine-jdk AS builder
ARG SKIP_TESTS=true
WORKDIR /app
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN if [ "$SKIP_TESTS" = "true" ]; then \
        ./gradlew build -x test; \
    else \
        ./gradlew build; \
    fi

FROM amazoncorretto:21-alpine-jdk
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
